-- 제품 구매를 취소 했을 때 트리거

USE SHOPPINGMALL2;

DROP TRIGGER IF EXISTS UPDATE_BUY;
DELIMITER // 
CREATE TRIGGER UPDATE_BUY AFTER UPDATE
ON BUY 
FOR EACH ROW
BEGIN 
-- 제품 수량
	IF NEW.BU_AMOUNT = OLD.BU_AMOUNT AND NEW.BU_STATE = '구매취소' THEN
		UPDATE PRODUCT 
			SET PR_AMOUNT = PR_AMOUNT + OLD.BU_AMOUNT 
		WHERE PR_NUM = OLD.BU_PR_NUM;
	ELSE 
		IF NEW.BU_AMOUNT  !=OLD.BU_AMOUNT THEN
			UPDATE PRODUCT 
				SET PR_AMOUNT = PR_AMOUNT + OLD.BU_AMOUNT - NEW.BU_AMOUNT
			WHERE PR_NUM = OLD.BU_PR_NUM;
		END IF;
	END IF;
END // 
DELIMITER ;
UPDATE BUY SET BU_STATE = '구매취소' WHERE BU_NUM = '1';
UPDATE BUY SET BU_AMOUNT = 2 WHERE BU_NUM = 'QWE202212211712';
